#ifndef IMGENGINE_INCLUDE_API_V1_IMG_PIPELINE_WRAPPER_H
#define IMGENGINE_INCLUDE_API_V1_IMG_PIPELINE_WRAPPER_H

#include "../../../api/v1/img_pipeline.h"

#endif /* IMGENGINE_INCLUDE_API_V1_IMG_PIPELINE_WRAPPER_H */
