#ifndef IMGENGINE_INCLUDE_API_V1_IMG_PLUGIN_API_WRAPPER_H
#define IMGENGINE_INCLUDE_API_V1_IMG_PLUGIN_API_WRAPPER_H

#include "../../../api/v1/img_plugin_api.h"

#endif /* IMGENGINE_INCLUDE_API_V1_IMG_PLUGIN_API_WRAPPER_H */
