#ifndef IMGENGINE_INCLUDE_API_V1_IMG_ERROR_WRAPPER_H
#define IMGENGINE_INCLUDE_API_V1_IMG_ERROR_WRAPPER_H

#include "../../../api/v1/img_error.h"

#endif /* IMGENGINE_INCLUDE_API_V1_IMG_ERROR_WRAPPER_H */
