#ifndef IMGENGINE_OPCODES_H
#define IMGENGINE_OPCODES_H

// 🔥 CORE ENGINE OPCODES (GLOBAL CONTRACT)

#define OP_RESIZE 0x01
#define OP_CROP 0x02
#define OP_GRAYSCALE 0x03

// 🔥 SEPARABLE (HOT PATH)
#define OP_RESIZE_H 0x10
#define OP_RESIZE_V 0x11

#endif